### ISSUE TITLE
Default second author name in PDF metadata

### ISSUE THREAD

**Issue by micskeiz** [FTSRG/thesis-template-latex#19]
src/include/preamble.tex contains the following for pdf metadata:

    pdfauthor={\vikszerzoA \tdkszerzoB}

However, in the usual BSc/MSc thesis setup suthors only update \vikszerzoA and they do not even see \tdkszerzoB, thus it remains "Második Szerző". (I have seen it is several submitted document)

Suggestions:
 * remove \tdkszerzoB from here, or
 * set \tdkszerzoB to empty string (those who need it, would set it anyway)

**Comment by szarnyasg** [comment]
Thanks! I did some experiments but getting it right for all cases would require a lot of LaTeX code so in the end I created a variable for this.
I also removed the default list of keywords (`kulcsszó1, kulcsszó2, kulcsszó3`).
