### ISSUE TITLE
Author name appears in wrong order in Declaration for English theses

### ISSUE THREAD

**Issue by molnargab** [FTSRG/thesis-template-latex#20]
The theses of the university require a formal declaration of own work. I think this needs to be in Hungarian even if the language of the thesis is English. However it raises a conflict, because `\vikszerzoA` needs to be in the English order for the titlepage. 

It would be good if the template could handle this.

I see these solutions so far:
   * Have a different command for the declaration. For Hungarian this could be defaulted to `\vikszerzoA`. For English this should be provided by the users.
   * Let's define a command for first name and last name each, and derive the names for the titlepage and declaration accordingly: declaration would always use the Hungarian order, the titlepage would use the language dependent order.

**Comment by szarnyasg** [comment]
Thanks for reporting this!

> Let's define a command for first name and last name each, and derive the names for the titlepage and declaration accordingly: declaration would always use the Hungarian order, the titlepage would use the language dependent order.

I think this is the more elegant solution and it was quite straightforward to implement.
