### ISSUE TITLE
Line spacing command is issued in the wrong file

### ISSUE THREAD

**Issue by lpeter91** [FTSRG/thesis-template-latex#27]
Removing the "\include{include/guideline}" from diploma.tex sets back line spacing to normal for the whole text, since the "\onehalfspacing" command is issued in guideline.tex. While in reality it looks way better with the regular spacing, still the officially expected one is 1.5. (Fixing this bug is a great way to boost the total number of pages. :P) Command should be issued "elsewhere".

**Comment by szarnyasg** [comment]
Finally got back to this issue. We are also not a fan of \onehalfspacing, so single spacing it is.

**Comment by lpeter91** [comment]
Cool, thank you!
