### ISSUE TITLE
Paragraph indentation got mixed up

### ISSUE THREAD

**Issue by lpeter91** [FTSRG/thesis-template-latex#28]
Commit 7e9cf71c5ed566153416ee2d110d58daa8218702  also mixed up Hungarian/English paragraph indentation. Just compare earlier builds with the current one. In the latest build some space is skipped after each paragraph, and there's no indentation for the first lines (with Hungarian settings).

**Comment by szarnyasg** [comment]
@lpeter91 Thanks for the issues! These are not difficult to fix, but I'd like to discuss them with the other advisors and check the official rules. I think I'll get back to these in the beginning of the next semester. Feel free to submit more issues if you encounter any.

**Comment by szarnyasg** [comment]
A related issue: we should also fix the spacing between paragraphs.
