### ISSUE TITLE
Alapértelmezett aláosztások számának módosítása

### ISSUE THREAD

**Issue by AdamDomafoldi** [FTSRG/thesis-template-latex#48]
> A fejezeteket decimális aláosztással számozzuk, maximálisan 3 aláosztás mélységben (pl. 2.3.4.1.). 

Alapértelmezetetten a subsubsection alfejezet nem számozva jelenik meg. 

A premable fájlban ez látható a setcounter beállításnál:

```
\setcounter{secnumdepth}{0}
%\sectionfont{\large\upshape\bfseries}
\setcounter{secnumdepth}{2}
```
Javasolni szeretném a `\setcounter{secnumdepth}{2}`értékét 2-ről 3-ra módosítani. Ezt követően a subsubsection már számozva jelenik meg. 

Valamint a \setcounter beállítás kétszer kap értéket, először 0 majd 2 értéket. Rögtön egymás után. Javaslom az egyik törlését.

**Comment by szarnyasg** [comment]
Jogos, köszi az észrevételeket. A négyszintű hierarchia számozása ízlés kérdése is, de betehetjük, legfeljebb kikapcsolja az, akinek nem tetszik (én 1.2.3. szintet használtam a [diptervemben](http://docs.inf.mit.bme.hu/thesis-works/pdfs/szarnyas-gabor-msc.pdf), de az egy régebbi sablon volt).

Tudsz esetleg PR-t küldeni róla?

**Comment by AdamDomafoldi** [comment]
Most este futottam bele a problémába. Mivel a doksi szerint mehet a 4 szint, így először nem értettem a problémát (tapasztalatlan latex-es vagyok még).

Holnap este küldök pull requestet a módosításokkal.

**Comment by AdamDomafoldi** [comment]
Ment a pull request:
https://github.com/FTSRG/thesis-template-latex/pull/49

**Comment by szarnyasg** [comment]
Merge-oltem, koszi!
