### ISSUE TITLE
Changing to a more detailed/modern bibtex style

### ISSUE THREAD

**Issue by micskeiz** [FTSRG/thesis-template-latex#51]
Currently we use `plain`, which lacks several features (e.g. handling doi or url natively).

I recommend to switch to a more feature complete bib style. For example:
 
1. Natbib
```
\usepackage[numbers]{natbib}
...
\bibliographystyle{abbrvnat}
```

Provides native doi and url support, is also numbered and ordered, does not require any modification in compiling, natbib has a decent documentation.

2. Biblatex/biber
- Pro: has a proper definition of entry fields in the manual (there is no standard definition for bibtex!), supports all modern entry types and fields, lots of functionality compared to bibtex
- Con: breaks build, requires `biber` instead of `bibtex` for some features

**Comment by szarnyasg** [comment]
Good idea, but I'd stop at natbib. I repeatedly found biber is difficult to port across different TeX development environments (and usually just use a Makefile to build such documents). However, I am not sure how well it works with huplain.

I started experimenting here: https://github.com/FTSRG/thesis-template-latex/tree/natbib

**Comment by micskeiz** [comment]
OK, natbib could be a good compromise. Even if it does not work for huplain, we could add it just for the english langauge.

**Comment by szarnyasg** [comment]
We tried this for a thesis work last week. It worked well but I found one small issue. Using the plainnat style, for references from DBLP entries (which are widely considered as high-quality), the DOI is duplicated as it appears both because of the doi and url fields. Removing the url field (or changing it to xxurl) solves this issue.
