### ISSUE TITLE
Dupla oldalas beállításnál extra üres oldalak szúródnak be

### ISSUE THREAD

**Issue by AdamDomafoldi** [FTSRG/thesis-template-latex#54]
Eddig az egyoldalas beállítást használtam:
`\documentclass[11pt,a4paper,oneside]{report}             % Single-side`

De mivel kötelező a kétoldalas nyomtatás, így ezt a sort kommenteltem ki:
`\documentclass[11pt,a4paper,twoside,openright]{report}  % Duplex`

A probléma az, hogy a táblázatok jegyzések, ábrák jegyzéke és a köszönetnyilvánítás fejezetek után üres oldalakat szúr be. Ez nekem extra 5 üres oldalt jelent. Ha visszaállítom egyoldalasra, akkor a probléma megszűnik.

Mi lehet a megoldás erre? Egyáltalán a sablon hibája ez? Sharelatexel (online) használom, gond eddig nem volt vele és nincs compilation warnig se error. 

Edit: Minden fejezet után beszúr nekem egy üres oldalt.

Edit2: az openright törlésével a probléma megszűnik, nem tudom, hogy ez tudatos-e vagy véletlenül maradt-e bent. Amennyiben tudatos, akkor bocsánat a felesleges issue-ért. 
` \documentclass[11pt,a4paper,twoside]{report}  % Duplex`

**Comment by szarnyasg** [comment]
Köszi az issue ticketet! Komolyabban most nem tudom beleásni magam a dologba, de fontos, hogy a sablont lehet lazán értelmezni, szóval nyugodtan ki lehet kapcsolni az `openright` beállítást.

**Comment by AdamDomafoldi** [comment]
Szerintem is egy komment mehetne kiegészítésképpen oda, ha gondoljátok csinálhatok pull requestet hozzá. @spinakker által elmondottak világossá teszik a paraméter értelmét.

**Comment by szarnyasg** [comment]
Támogatom!
