### ISSUE TITLE
Missing T1/lmtt/l/sl shape causing issues in lstlisting

### ISSUE THREAD

**Issue by leventerevesz** [ftsrg/thesis-template-latex#60]
**Platform**: linux texlive pdflatex
**Steps to reproduce**: insert an *lstlisting* with eg. `[language=C]` option and write a comment in it

*lstlisting* cannot display slanted text (code comments) when using the default lmodern lighttt typeface. The build crashes with this error:

> No declaration for shape T1/lmtt/l/sl.
sub@sfcnt ...e forspace shapespace mandatory@arg }

I have found [a solution](https://tex.stackexchange.com/questions/234003/italic-font-in-lmodern-lighttt) on Stackexchange:

> That's a bug in the fd-files (OT1lmtt.fd and T1lmtt.fd): In the "lighttt" section they substitute the lmtt/m/it to lmtt/l/sl instead of lmtt/m/sl. You should report it.
>You can get around it with
```latex
\documentclass{article}
\usepackage[lighttt]{lmodern}
\ttfamily\DeclareFontShape{T1}{lmtt}{m}{it}{<->sub*lmtt/m/sl}{}

\begin{document}
Abc {\ttfamily abc  \itshape abc}
\end{document}
```

It seems to be fixing the problem, the build succeeds after inserting that line.

**Comment by szarnyasg** [comment]
@leventerevesz cool, can you turn this in to a PR?
