### ISSUE TITLE
No space between VIK konzulens Megszolitas and Keresztnev

### ISSUE THREAD

**Issue by radl97** [ftsrg/thesis-template-latex#65]
Expected usage:

```
\newcommand{\vikkonzulensAMegszolitas}{Dr.}
\newcommand{\vikkonzulensAVezeteknev}{Hajdu}
\newcommand{\vikkonzulensAKeresztnev}{Ákos}
```

What works right now:

```
\newcommand{\vikkonzulensAMegszolitas}{Dr.~}
\newcommand{\vikkonzulensAVezeteknev}{Hajdu}
\newcommand{\vikkonzulensAKeresztnev}{Ákos}
```

Related line in thesis-en.tex:

`\newcommand{\vikkonzulensA}{\vikkonzulensAMegszolitas\vikkonzulensAKeresztnev{} \vikkonzulensAVezeteknev}`

**Comment by szarnyasg** [comment]
`dr.~` is the default now: https://github.com/ftsrg/thesis-template-latex/blob/master/src/thesis.tex#L10
