### ISSUE TITLE
No spacing between title and first name in supervisor's name

### ISSUE THREAD

**Issue by leventeBajczi** [ftsrg/thesis-template-latex#69]
I don't know if this is deliberate, but using the template the supervisor's name is not properly spaced.
E.g., `Dr.Firstname Lastname` is used instead of `Dr. Firstname Lastname`.
https://github.com/ftsrg/thesis-template-latex/blob/183a24f54b176558ef01dc39b1abe143ceeb6c73/src/include/thesis-en.tex#L35

**Comment by szarnyasg** [comment]
Not sure why this is the case but I remember this being an issue. IIRC we used `Dr.~` to work around this.

**Comment by leventeBajczi** [comment]
Oh, I guess this is so that names with no titles do not get an extra whitespace before their first names. Thanks for the response, I'm closing this issue.
