### ISSUE TITLE
Onehalf spacing?

### ISSUE THREAD

**Issue by radl97** [ftsrg/thesis-template-latex#70]
The thesis expects 1.5 line spacing:

![IMG_20220501_115826_094](https://user-images.githubusercontent.com/7879888/166141063-f8af36be-8cde-4920-b803-cc1f7401062a.jpg)

https://github.com/ftsrg/thesis-template-latex/blob/183a24f54b176558ef01dc39b1abe143ceeb6c73/src/content/thesis-format.tex#L22

It seems to be, though, that the resulting document uses single spacing.

**Comment by szarnyasg** [comment]
Thanks! The document indeed uses single spacing instead of `\onehalfspacing`. In general, most scientific works use single spacing and this template should stick to that. I'll push a commit to fix this.

**Comment by radl97** [comment]
Are students permitted to change to onehalf spacing?

It seems wrong to me to fix with rewriting the thesis requirements. Note that previously this matched the VIK guideline from dipterv.vik.bme.hu. I suggest noting the issue here:

`[...] talpas betűtípussal és egyszeres sorközzel célszerű elkészíteni. A \onehalfspacing beállítással másfeles sorköz is elfogadott szakdolgozatokban és diplomamunkákban, de ajánlott megtartani az egyszeres sorközt.`

Or somrthing like that.

**Comment by szarnyasg** [comment]
Good point, I clarified that. In practice, I have never heard anybody complain about single line spacing. I have heard people complaining about egregiously large line spacing -- double line spacing is definitely too much for a thesis and is perceived as an attempt to increase the page count without creating more content. One-half spacing falls in the middle. In rare cases, some reviewers may note it but it's unlikely that this will be anything more than a minor remark in the review.
